openapi: 3.0.3
info:
  version: 1.0.0
  title: Restmenu REST interface
  description: >
    This interface description describes the Restmenu REST internal interface.
tags:
  - name: Restmenu
    description: Restmenu REST interface.

paths:
  /restaurants:
    get:
      operationId: getRestaurants
      parameters:
        - name: name
          in: query
          required: false
          schema:
            type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RestaurantDto"

servers:
  - url: http://localhost/api/v1
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    RestaurantDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Restaurant ABC
        description:
          type: string
          example: A burger Restaurants
security:
  - basicAuth: []
