openapi: 3.0.3
info:
  version: 1.0.0
  title: Restmenu REST interface
  description: >
    This interface description describes the Restmenu REST internal interface.
tags:
  - name: Restmenu
    description: Restmenu REST interface.
paths:
  /greeting:
    get:
      tags:
        - Greeting
      summary: Get a greeting
      description: Get a greeting
      operationId: getGreeting
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GreetingDto"
servers:
  - url: http://localhost/v1
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    GreetingDto:
      type: object
      description: A user
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Max
security:
  - basicAuth: []
