spring:
  application:
    name: restmenu-server

  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:restmenu
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      use-new-id-generator-mappings: false
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: validate
    show-sql: true

  liquibase:
    change-log: classpath:/changelog/database-schema.xml

  h2:
    console:
      enabled: true
      path: /h2-console
